version: "3"
services:
  app:
    container_name: umbrella-backend-project
    env_file:
      - env.list
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
    #environment:
    #  - DEBUG
    #depends_on:
    #  - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      # Persist the container's MongoDB /data/db within local host folder
      #- ./data/db:/data/db
      - ~/Dev/mongodb/data/db:/data/db